// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//  Sprite animation.
//
//-----------------------------------------------------------------------------

#pragma once

// Basic data types.
// Needs fixed point, and BAM angles.
#include "../doomtype.h" // toIndex, for numPSprites below
#include "../Math/FixedPoint.h"
#include "../Math/TrigTables.h"

// Needs to include the precompiled
// sprite animation tables.
// Header generated by multigen utility.
// This includes all the data for thing animation,
// i.e. the Thing Atrributes table
// and the Frame Sequence table.
#include "Info.h"

namespace Doom
{
//
// Frame flags:
// handles maximum brightness (torches, muzzle flare, light sources)
//
constexpr int FF_FULLBRIGHT = 0x8000; // flag in thing->frame
constexpr int FF_FRAMEMASK = 0x7fff;
} // namespace Doom

//
// Overlay psprites are scaled shapes
// drawn directly on the view screen,
// coordinates are given for a 320*200 view screen.
//
namespace Doom
{
enum class PspNum
{
    Weapon,
    Flash,
    NumPSprites
};

constexpr int numPSprites = toIndex(PspNum::NumPSprites);
} // namespace Doom

namespace Doom
{
struct PspDef
{
    State* state; // a 0 state means not active
    int tics;
    Fixed sx;
    Fixed sy;
};
} // namespace Doom

//-----------------------------------------------------------------------------
//
// $Log:$
//
//-----------------------------------------------------------------------------
