// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//        DOOM main program (doomMain) and game loop (doomLoop),
//        plus functions to determine game mode (shareware, registered),
//        parse command line parameters, configure game parameters (turbo),
//        and call the startup functions.
//
//-----------------------------------------------------------------------------

#include "../Host/Platform.h"

#if defined(DOOM_WIN32)

#define X_OK 0
#define W_OK 2
#define R_OK 4
#define RW_OK 6
#elif defined(DOOM_APPLE)

#endif

#include "GameDefs.h"
#include "MapSpawns.h"
#include "Strings.h"
#include "SoundData.h"
#include "../Wad/WadFile.h"
#include "../UI/Wipe.h"
#include "Args.h"
#include "ConfigTypes.h"
#include "../UI/Menu.h"
#include "../UI/Hud.h"
#include "../UI/IntermissionTypes.h"
#include "../UI/StatusBarTypes.h"
#include "../UI/AutomapTypes.h"
#include "DoomMain.h"

#include "AttractMode.h"
#include "DoomMain.h"
#include "ConfigPaths.h"

#include <ea_data_structures/Structures/Array.h>
#include <ea_data_structures/Structures/Vector.h>
#include "DemoState.h"
#include "DisplayState.h"
#include "EngineParams.h"
#include "EventQueue.h"
#include "GameClock.h"
#include "GameFlow.h"
#include "GameSession.h"
#include "GameVersion.h"
#include "LaunchOptions.h"
#include "MovementSpeeds.h"
#include "NetState.h"
#include "PlayerState.h"
#include "RefreshFlags.h"
#include "SoundSettings.h"
#include "StartupDefaults.h"

#include "../Render/Draw.h"
#include "../Render/Video.h"
#include "../Sim/Setup.h"
#include "../UI/Automap.h"
#include "../UI/Finale.h"
#include "../UI/Hud.h"
#include "../UI/Intermission.h"
#include "../UI/StatusBar.h"
#include "../UI/Wipe.h"
#include "Args.h"
#include "Config.h"
#include "Net.h"
#include "../Host/Sound.h"
#include "../UI/Menu.h"
#include "../Host/Video.h"
#include "../Host/System.h"
#include "../Game/OverlayState.h"
#include "../Render/Main.h"
#include "../Render/ViewWindow.h"
#include "Game.h"
#include "Sound.h"

// The boot-time WAD list, file-local: Doom::addWadFile appends to it and Doom::initWadFiles
// consumes it, and nothing outside this file reads it (its d_main.h extern is gone).
//
// wadFileStorage owns each filename; wadfiles is the char* view Doom::initWadFiles wants,
// refreshed after every push (Step 9 strand (b)). wadFileStorage is reserved to
// MAXWADFILES up front, in addWadFile, so a push never reallocates the outer vector and
// never moves an already-published inner buffer out from under a stored view pointer.
static EA::Vector<EA::Vector<char>> wadFileStorage;
static char* wadfiles[Doom::MAXWADFILES];

// The command-line launch flags are a Doom::LaunchOptions owned by the Engine now; these
// are references onto it (REFACTOR.md, Step 5).

// (drone, an always-unread vestige, was deleted here - the Doom::DoomCom.drone in d_net.h
// is an unrelated struct member.)

// singletics / debugfile are Doom::EngineParams owned by the Engine now; these are references onto
// it (REFACTOR.md, Step 5).

// The new-game defaults are a Doom::StartupDefaults owned by the Engine now; these are
// references onto it (REFACTOR.md, Step 5).

// advancedemo is a Doom::AttractMode member owned by the Engine now; this reference stays
// because d_main.h still externs it for Tests/SimProbe (REFACTOR.md, Step 5). Its
// demosequence/pagetic siblings had no reader outside this file and are gone; pagename's
// reference is below, kept for g_game.

// wadfile[]/mapdir[] were dead (referenced only in comments) and are deleted, the
// linecount/loopcount/viewangleoffset way. basedefault is an Engine member now
// (Game/ConfigPaths.h) - it was never actually config-blocked, since defaults[] does
// not capture its address (defaultfile is assigned it at runtime, not bound to it).

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
// The input event ring buffer is a Doom::EventQueue owned by the Engine now; these vanilla
// names are references onto it (events[] as a reference-to-array).

// wipegamestate (with gamestate) is a Doom::GameFlow owned by the Engine now; this is a
// reference onto it. It can be set to -1 to force a wipe on the next draw.
void Doom::executeSetViewSize();

// print title for every printed line - file-local, built and printed only here
static EA::Array<char, 128> title;

// Title/demo-loop state: a member of the Doom::AttractMode above, still read by g_game
// through its own extern declaration.

// Other subsystems' globals/functions this file reaches (at global scope so the
// namespace code below binds :: not Doom::).
extern void* statcopy; // g_game
void Doom::checkNetGame();
void Doom::buildTiccmd(Doom::Ticcmd* cmd);

namespace Doom
{

constexpr int MAXARGVS = 100;

// Forward declarations so call order needs no rearranging.
void doomLoop();
void processEvents();
void doAdvanceDemo();

//
// postEvent
// Called by the I/O functions when input is detected
//
void postEvent(Event* ev)
{
    auto& events_ = eventQueue();

    events_.events[events_.eventhead] = *ev;
    events_.eventhead++;
    events_.eventhead = (events_.eventhead) & (MAXEVENTS - 1);
}

//
// processEvents
// Send all the events of the given timestamp down the responder chain
//
void processEvents()
{
    Event* ev;

    auto& events_ = eventQueue();

    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ((gameVersion().gamemode == commercial) && (Doom::wad().find("map01") < 0))
        return;

    for (; events_.eventtail != events_.eventhead;)
    {
        ev = &events_.events[events_.eventtail];
        if (!menuResponder(ev))
            Doom::gameResponder(ev);
        // else menu ate the event
        events_.eventtail++;
        events_.eventtail = (events_.eventtail) & (MAXEVENTS - 1);
    }
}

//
// displayFrame
//  draw current display, possibly wiping it from the previous
//
void displayFrame()
{
    auto& view = viewWindow();
    auto& overlay = overlayState();

    // The frame-diff state machine: a Doom::DisplayState owned by the Engine now, reached by local
    // references (formerly displayFrame's own function-local statics, never reset - identical
    // persistence).
    DisplayState& ds = displayState();
    bool& viewactivestate = ds.viewactivestate;
    bool& menuactivestate = ds.menuactivestate;
    bool& inhelpscreensstate = ds.inhelpscreensstate;
    bool& fullscreen = ds.fullscreen;
    GameState& oldgamestate = ds.oldgamestate;
    int& borderdrawcount = ds.borderdrawcount;
    int y;
    bool wipe;
    bool redrawsbar;

    auto& flow = gameFlow();
    auto& clock = gameClock();
    auto& refresh = refreshFlags();

    if (refresh.nodrawers)
        return; // for comparative timing / profiling

    redrawsbar = false;

    // change the view size if needed
    if (view.setsizeneeded)
    {
        Doom::executeSetViewSize();
        oldgamestate = static_cast<GameState>((-1)); // force background redraw
        borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (flow.gamestate != flow.wipegamestate)
    {
        wipe = true;
        Doom::startScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
        wipe = false;

    if (flow.gamestate == GS_LEVEL && clock.gametic)
        Doom::eraseHud();

    // do buffered drawing
    switch (flow.gamestate)
    {
        case GS_LEVEL:
            if (!clock.gametic)
                break;
            if (overlay.automapactive)
                Doom::drawAutomap();
            if (wipe || (view.viewheight != 200 && fullscreen))
                redrawsbar = true;
            if (inhelpscreensstate && !overlay.inhelpscreens)
                redrawsbar = true; // just put away the help screen
            Doom::drawStatusBar(view.viewheight == 200, redrawsbar);
            fullscreen = view.viewheight == 200;
            break;

        case GS_INTERMISSION:
            Doom::drawIntermission();
            break;

        case GS_FINALE:
            Doom::drawFinale();
            break;

        case GS_DEMOSCREEN:
            drawPage();
            break;
    }

    // draw buffered stuff to screen
    updateNoBlit();

    // draw the view directly
    if (flow.gamestate == GS_LEVEL && !overlay.automapactive && clock.gametic)
    {
        auto& state = playerState();
        Doom::renderPlayerView(state.players[state.displayplayer]);
    }

    if (flow.gamestate == GS_LEVEL && clock.gametic)
        Doom::drawHud();

    // clean up border stuff
    if (flow.gamestate != oldgamestate && flow.gamestate != GS_LEVEL)
        setPalette(static_cast<byte*>((Doom::cacheLumpName("PLAYPAL"))));

    // see if the border needs to be initially drawn
    if (flow.gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
        viewactivestate = false; // view was not active
        Doom::fillBackScreen(); // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (flow.gamestate == GS_LEVEL && !overlay.automapactive
        && view.scaledviewwidth != 320)
    {
        if (overlay.menuactive || menuactivestate || !viewactivestate)
            borderdrawcount = 3;
        if (borderdrawcount)
        {
            Doom::drawViewBorder(); // erase old menu stuff
            borderdrawcount--;
        }
    }

    menuactivestate = overlay.menuactive;
    viewactivestate = refresh.viewactive;
    inhelpscreensstate = overlay.inhelpscreens;
    oldgamestate = flow.wipegamestate = flow.gamestate;

    // draw pause pic
    if (refresh.paused)
    {
        if (overlay.automapactive)
            y = 4;
        else
            y = view.viewwindowy + 4;
        Doom::drawPatchDirect(view.viewwindowx + (view.scaledviewwidth - 68) / 2,
                              y,
                              0,
                              static_cast<Patch*>((Doom::cacheLumpName("M_PAUSE"))));
    }

    // menus go directly to the screen
    drawMenu(); // menu is drawn even on top of everything
    Doom::netUpdate(); // send out any new accumulation

    // normal update
    flow.is_wiping_screen = wipe;
    if (!wipe)
    {
        finishUpdate(); // page flip or blit buffer
        return;
    }

    // wipe update
    Doom::endScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

#if 0 // [pd] Moved to updateWipe
    do
    {
        do
        {
            nowtime = currentTic();
            tics = nowtime - wipestart;
        } while (!tics);
        wipestart = nowtime;
        done = Doom::screenWipe(wipe_Melt
                               , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
        updateNoBlit();
        drawMenu();                            // menu is drawn even on top of wipes
        finishUpdate();                      // page flip or blit buffer
    } while (!done);
#endif
}

//
//  doomLoop
//
void updateWipe()
{
    if (Doom::screenWipe(wipe_Melt, 0, 0, SCREENWIDTH, SCREENHEIGHT, 1))
        gameFlow().is_wiping_screen = false;
}

void doomLoop()
{
#if 0 // [pd] Moved to doomMain()
    if (demorecording)
        Doom::beginRecording();

    if (Doom::checkParm("-debugfile"))
    {
        EA::Array<char, 20> filename;
        //doom_sprintf(filename, "debug%i.txt", consoleplayer);
        doom_print("debug output to: %s\n", filename.data());
        debugfile = doom_open(filename.data(), "w");
    }

    initGraphics();
#endif

    auto& state = playerState();

    // while (1)
    {
        // frame syncronous IO operations
        startFrame();

        // process one or more tics
        if (engineParams().singletics)
        {
            auto& net = netState();
            auto& clock = gameClock();

            startTic();
            processEvents();
            Doom::buildTiccmd(
                &net.netcmds[state.consoleplayer][net.maketic % BACKUPTICS]);
            if (attractMode().advancedemo)
                doAdvanceDemo();
            menuTicker();
            Doom::gameTicker();
            clock.gametic++;
            net.maketic++;
        }
        else
        {
            Doom::tryRunTics(); // will run at least one tic
        }

        // move positional sounds
        Doom::updateSounds(state.players[state.consoleplayer].mo);

        // Update display, next frame, with current state.
        displayFrame();

#if 0 // [pd] Sound is queried by the application's audio thread.
        // Sound mixing for the buffer is snychronous.
        updateSound();

        // Synchronous sound output is explicitly called.
        // Update sound output.
        submitSound();
#endif
    }
}

//
//  DEMO LOOP
//

//
// pageTicker
// Handles timing for warped projection
//
void pageTicker()
{
    if (--attractMode().pagetic < 0)
        advanceDemo();
}

//
// drawPage
//
void drawPage()
{
    Doom::drawPatch(
        0, 0, 0, static_cast<Patch*>((Doom::cacheLumpName(attractMode().pagename))));
}

//
// advanceDemo
// Called after each demo or intro demosequence finishes
//
void advanceDemo()
{
    attractMode().advancedemo = true;
}

//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
void doAdvanceDemo()
{
    auto& state = playerState();
    auto& attract = attractMode();
    auto& flow = gameFlow();
    const GameMode gamemode = gameVersion().gamemode;

    state.players[state.consoleplayer].playerstate = PST_LIVE; // not reborn
    attract.advancedemo = false;
    demoState().usergame = false; // no save / end game here
    refreshFlags().paused = false;
    flow.gameaction = ga_nothing;

    if (gamemode == retail)
        attract.demosequence = (attract.demosequence + 1) % 7;
    else
        attract.demosequence = (attract.demosequence + 1) % 6;

    switch (attract.demosequence)
    {
        case 0:
            if (gamemode == commercial)
                attract.pagetic = 35 * 11;
            else
                attract.pagetic = 170;
            flow.gamestate = GS_DEMOSCREEN;
            attract.pagename = "TITLEPIC";
            if (gamemode == commercial)
                Doom::startMusic(mus_dm2ttl);
            else
                Doom::startMusic(mus_intro);
            break;
        case 1:
            Doom::deferPlayDemo("demo1");
            break;
        case 2:
            attract.pagetic = 200;
            flow.gamestate = GS_DEMOSCREEN;
            attract.pagename = "CREDIT";
            break;
        case 3:
            Doom::deferPlayDemo("demo2");
            break;
        case 4:
            flow.gamestate = GS_DEMOSCREEN;
            if (gamemode == commercial)
            {
                attract.pagetic = 35 * 11;
                attract.pagename = "TITLEPIC";
                Doom::startMusic(mus_dm2ttl);
            }
            else
            {
                attract.pagetic = 200;

                if (gamemode == retail)
                    attract.pagename = "CREDIT";
                else
                    attract.pagename = "HELP2";
            }
            break;
        case 5:
            Doom::deferPlayDemo("demo3");
            break;
            // THE DEFINITIVE DOOM Special Edition demo
        case 6:
            Doom::deferPlayDemo("demo4");
            break;
    }
}

//
// startTitle
//
void startTitle()
{
    gameFlow().gameaction = ga_nothing;
    attractMode().demosequence = -1;
    advanceDemo();
}

//
// addWadFile
//
void addWadFile(const char* file)
{
    int numwadfiles;

    for (numwadfiles = 0; wadfiles[numwadfiles]; numwadfiles++)
        ;

    wadFileStorage.reserveAtLeast(MAXWADFILES);

    auto& newfile = wadFileStorage.create(doom_strlen(file) + 1);
    doom_strcpy(newfile.data(), file);

    wadfiles[numwadfiles] = newfile.data();
}

// Joins the WAD directory and a leading-slash basename into one owned string.
// The point of it is that the size comes from the two strings themselves rather
// than from a number written beside them - see the note at the call sites, where
// one of seven such numbers was wrong and overflowed the buffer by a byte.
static EA::Vector<char> joinWadPath(const char* directory, const char* file)
{
    EA::Vector<char> path(doom_strlen(directory) + doom_strlen(file) + 1);

    doom_strcpy(path.data(), directory);
    doom_concat(path.data(), file);

    return path;
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion()
{
    // const because the Windows branch assigns a string literal to it. Writing
    // through a char* aimed at one is undefined, and only ever compiled at all
    // because C++ allowed the conversion until C++11 removed it.
    const char* home;

    auto& version = gameVersion();
    auto& opts = launchOptions();
    auto& paths = configPaths();

    const char* doomwaddir = doom_getenv("DOOMWADDIR");
    if (!doomwaddir)
        doomwaddir = ".";

    // Each of these was sized by hand, as `strlen(dir) + 1 + <basename> + 1`
    // with the basename's length written out as a literal - and one of the seven
    // had it wrong. "doomu.wad" is nine characters and was counted as eight, so
    // building the retail path wrote its terminating NUL one byte past the
    // allocation, every single boot.
    //
    // It went unseen because it depends entirely on what the allocator puts
    // there: on macOS the block's own padding absorbed it, while on Windows
    // arm64 it corrupted the following block and demo1 and demo3 died with a
    // segfault before rendering a frame. AddressSanitizer names it in one line.
    // Nothing above the allocator could see it - the goldens hash the world and
    // the picture, and both were correct right up until the heap gave out.
    //
    // So the literal is gone rather than corrected: joinWadPath measures the
    // string it is about to write, which is the only count that cannot disagree
    // with it.
    const auto doom2wad = joinWadPath(doomwaddir, "/doom2.wad"); // Commercial.
    const auto doomuwad = joinWadPath(doomwaddir, "/doomu.wad"); // Retail.
    const auto doomwad = joinWadPath(doomwaddir, "/doom.wad"); // Registered.
    const auto doom1wad = joinWadPath(doomwaddir, "/doom1.wad"); // Shareware.
    const auto plutoniawad = joinWadPath(doomwaddir, "/plutonia.wad");
    const auto tntwad = joinWadPath(doomwaddir, "/tnt.wad");
    const auto doom2fwad = joinWadPath(doomwaddir, "/doom2f.wad"); // French.

#if !defined(DOOM_WIN32)
    home = doom_getenv("HOME");
    if (!home)
        fatalError("Error: Please set $HOME to your home directory");
#else
    home = ".";
#endif
    //doom_sprintf(basedefault, "%s/.doomrc", home);
    doom_strcpy(paths.basedefault.data(), home);
    doom_concat(paths.basedefault.data(), "/.doomrc");

    if (Doom::checkParm("-shdev"))
    {
        version.gamemode = shareware;
        opts.devparm = true;
        addWadFile(DEVDATA "doom1.wad");
        addWadFile(DEVMAPS "data_se/texture1.lmp");
        addWadFile(DEVMAPS "data_se/pnames.lmp");
        doom_strcpy(paths.basedefault.data(), DEVDATA "default.cfg");
        return;
    }

    if (Doom::checkParm("-regdev"))
    {
        version.gamemode = registered;
        opts.devparm = true;
        addWadFile(DEVDATA "doom.wad");
        addWadFile(DEVMAPS "data_se/texture1.lmp");
        addWadFile(DEVMAPS "data_se/texture2.lmp");
        addWadFile(DEVMAPS "data_se/pnames.lmp");
        doom_strcpy(paths.basedefault.data(), DEVDATA "default.cfg");
        return;
    }

    if (Doom::checkParm("-comdev"))
    {
        version.gamemode = commercial;
        opts.devparm = true;
        /* I don't bother
        if(plutonia)
            addWadFile (DEVDATA"plutonia.wad");
        else if(tnt)
            addWadFile (DEVDATA"tnt.wad");
        else*/
        addWadFile(DEVDATA "doom2.wad");

        addWadFile(DEVMAPS "cdata/texture1.lmp");
        addWadFile(DEVMAPS "cdata/pnames.lmp");
        doom_strcpy(paths.basedefault.data(), DEVDATA "default.cfg");
        return;
    }

    void* f;
    if ((f = doom_open(doom2fwad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = commercial;
        // C'est ridicule!
        // Let's handle languages in config files, okay?
        version.language = french;
        doom_print("French version\n");
        addWadFile(doom2fwad.data());
        return;
    }

    if ((f = doom_open(doom2wad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = commercial;
        addWadFile(doom2wad.data());
        return;
    }

    if ((f = doom_open(plutoniawad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = commercial;
        addWadFile(plutoniawad.data());
        return;
    }

    if ((f = doom_open(tntwad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = commercial;
        addWadFile(tntwad.data());
        return;
    }

    if ((f = doom_open(doomuwad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = retail;
        addWadFile(doomuwad.data());
        return;
    }

    if ((f = doom_open(doomwad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = registered;
        addWadFile(doomwad.data());
        return;
    }

    if ((f = doom_open(doom1wad.data(), "rb")))
    {
        doom_close(f);
        version.gamemode = shareware;
        addWadFile(doom1wad.data());
        return;
    }

    doom_print("Game mode indeterminate.\n");
    version.gamemode = indetermined;
}

//
// Find a Response File
//
void FindResponseFile()
{
    for (int i = 1; i < myargc; i++)
        if (myargv[i][0] == '@')
        {
            void* handle = nullptr;
            int size;
            int k;
            int index;
            int indexinfile;
            char* infile;
            char* file;
            char* moreargs[20];
            char* firstargv;

            // READ THE RESPONSE FILE INTO MEMORY
            handle = doom_open(&myargv[i][1], "rb");
            if (!handle)
            {
                doom_print("\nNo such response file!");
                doom_exit(1);
            }
            doom_print("Found response file %s!\n");
            doom_print(&myargv[i][1]);
            doom_print("!\n");
            doom_seek(handle, 0, DOOM_SEEK_END);
            size = doom_tell(handle);
            doom_seek(handle, 0, DOOM_SEEK_SET);
            file = static_cast<char*>((doom_malloc(size)));
            doom_read(handle, file, size * 1);
            doom_close(handle);

            // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
            for (index = 0, k = i + 1; k < myargc; k++)
                moreargs[index++] = myargv[k];

            firstargv = myargv[0];
            myargv = static_cast<char**>((doom_malloc(sizeof(char*) * MAXARGVS)));
            doom_memset(myargv, 0, sizeof(char*) * MAXARGVS);
            myargv[0] = firstargv;

            infile = file;
            indexinfile = k = 0;
            indexinfile++; // SKIP PAST ARGV[0] (KEEP IT)
            do
            {
                myargv[indexinfile++] = infile + k;
                while (k < size
                       && ((*(infile + k) >= ' ' + 1) && (*(infile + k) <= 'z')))
                    k++;
                *(infile + k) = 0;
                while (k < size && ((*(infile + k) <= ' ') || (*(infile + k) > 'z')))
                    k++;
            } while (k < size);

            for (k = 0; k < index; k++)
                myargv[indexinfile++] = moreargs[k];
            myargc = indexinfile;

            // DISPLAY ARGS
            doom_print(doom_itoa(myargc, 10));
            doom_print(" command-line args:\n");
            for (k = 1; k < myargc; k++)
            {
                //doom_print("%s\n", myargv[k]);
                doom_print(myargv[k]);
                doom_print("\n");
            }

            break;
        }
}

//
// doomMain
//
void doomMain()
{
    int p;
    EA::Array<char, 256> file;

    auto& version = gameVersion();
    auto& opts = launchOptions();
    auto& session = gameSession();
    auto& defaults_ = startupDefaults();

    FindResponseFile();

    IdentifyVersion();

    version.modifiedgame = false;

    opts.nomonsters = Doom::checkParm("-nomonsters");
    opts.respawnparm = Doom::checkParm("-respawn");
    opts.fastparm = Doom::checkParm("-fast");
    opts.devparm = Doom::checkParm("-devparm");
    if (Doom::checkParm("-altdeath"))
        session.deathmatch = 2;
    else if (Doom::checkParm("-deathmatch"))
        session.deathmatch = 1;

    switch (version.gamemode)
    {
        case retail:
            //doom_sprintf(title,
            //        "                         "
            //        "The Ultimate DOOM Startup v%i.%i"
            //        "                           ",
            //        VERSION / 100, VERSION % 100);
            doom_strcpy(title.data(),
                        "                         "
                        "The Ultimate DOOM Startup v");
            doom_concat(title.data(), doom_itoa(VERSION / 100, 10));
            doom_concat(title.data(), ".");
            doom_concat(title.data(), doom_itoa(VERSION % 100, 10));
            doom_concat(title.data(), "                           ");
            break;
        case shareware:
            //doom_sprintf(title,
            //        "                            "
            //        "DOOM Shareware Startup v%i.%i"
            //        "                           ",
            //        VERSION / 100, VERSION % 100);
            doom_strcpy(title.data(),
                        "                            "
                        "DOOM Shareware Startup v");
            doom_concat(title.data(), doom_itoa(VERSION / 100, 10));
            doom_concat(title.data(), ".");
            doom_concat(title.data(), doom_itoa(VERSION % 100, 10));
            doom_concat(title.data(), "                           ");
            break;
        case registered:
            //doom_sprintf(title,
            //        "                            "
            //        "DOOM Registered Startup v%i.%i"
            //        "                           ",
            //        VERSION / 100, VERSION % 100);
            doom_strcpy(title.data(),
                        "                            "
                        "DOOM Registered Startup v");
            doom_concat(title.data(), doom_itoa(VERSION / 100, 10));
            doom_concat(title.data(), ".");
            doom_concat(title.data(), doom_itoa(VERSION % 100, 10));
            doom_concat(title.data(), "                           ");
            break;
        case commercial:
            //doom_sprintf(title,
            //        "                         "
            //        "DOOM 2: Hell on Earth v%i.%i"
            //        "                           ",
            //        VERSION / 100, VERSION % 100);
            doom_strcpy(title.data(),
                        "                         "
                        "DOOM 2: Hell on Earth v");
            doom_concat(title.data(), doom_itoa(VERSION / 100, 10));
            doom_concat(title.data(), ".");
            doom_concat(title.data(), doom_itoa(VERSION % 100, 10));
            doom_concat(title.data(), "                           ");
            break;
            /*FIXME
                   case pack_plut:
                    sprintf (title,
                             "                   "
                             "DOOM 2: Plutonia Experiment v%i.%i"
                             "                           ",
                             VERSION/100,VERSION%100);
                    break;
                  case pack_tnt:
                    sprintf (title,
                             "                     "
                             "DOOM 2: TNT - Evilution v%i.%i"
                             "                           ",
                             VERSION/100,VERSION%100);
                    break;
            */
        default:
            //doom_sprintf(title,
            //        "                     "
            //        "Public DOOM - v%i.%i"
            //        "                           ",
            //        VERSION / 100, VERSION % 100);
            doom_strcpy(title.data(),
                        "                     "
                        "Public DOOM - v");
            doom_concat(title.data(), doom_itoa(VERSION / 100, 10));
            doom_concat(title.data(), ".");
            doom_concat(title.data(), doom_itoa(VERSION % 100, 10));
            doom_concat(title.data(), "                           ");
            break;
    }

    //doom_print("%s\n", title);
    doom_print(title.data());
    doom_print("\n");

    if (opts.devparm)
        doom_print(D_DEVSTR);

#if 0 // [pd] Ignore cdrom
    if (Doom::checkParm("-cdrom"))
    {
        doom_print(D_CDROM);
        mkdir("c:\\doomdata", 0);
        doom_strcpy(basedefault, "c:/doomdata/default.cfg");
    }
#endif

    // turbo option
    if ((p = Doom::checkParm("-turbo")))
    {
        int scale = 200;

        if (p < myargc - 1)
            scale = doom_atoi(myargv[p + 1]);
        if (scale < 10)
            scale = 10;
        if (scale > 400)
            scale = 400;
        //doom_print("turbo scale: %i%%\n", scale);
        doom_print("turbo scale: ");
        doom_print(doom_itoa(scale, 10));
        doom_print("%%\n");

        auto& speeds = movementSpeeds();
        speeds.forwardmove[0] = speeds.forwardmove[0] * scale / 100;
        speeds.forwardmove[1] = speeds.forwardmove[1] * scale / 100;
        speeds.sidemove[0] = speeds.sidemove[0] * scale / 100;
        speeds.sidemove[1] = speeds.sidemove[1] * scale / 100;
    }

    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = Doom::checkParm("-wart");
    if (p)
    {
        myargv[p][4] = 'p'; // big hack, change to -warp

        // Map name handling.
        switch (version.gamemode)
        {
            case shareware:
            case retail:
            case registered:
                //doom_sprintf(file, "~"DEVMAPS"E%cM%c.wad", myargv[p + 1][0], myargv[p + 2][0]);
                doom_strcpy(file.data(), "~" DEVMAPS "E");
                doom_concat(file.data(), doom_ctoa(myargv[p + 1][0]));
                doom_concat(file.data(), "M");
                doom_concat(file.data(), doom_ctoa(myargv[p + 2][0]));
                doom_concat(file.data(), ".wad");

                //doom_print("Warping to Episode %s, Map %s.\n", myargv[p + 1], myargv[p + 2]);
                doom_print("Warping to Episode ");
                doom_print(myargv[p + 1]);
                doom_print(", Map ");
                doom_print(myargv[p + 2]);
                doom_print(".\n");
                break;

            case commercial:
            default:
                p = doom_atoi(myargv[p + 1]);
                if (p < 10)
                {
                    //doom_sprintf(file, "~"DEVMAPS"cdata/map0%i.wad", p);
                    doom_strcpy(file.data(), "~" DEVMAPS "cdata/map0");
                    doom_concat(file.data(), doom_itoa(p, 10));
                    doom_concat(file.data(), ".wad");
                }
                else
                {
                    //doom_sprintf(file, "~"DEVMAPS"cdata/map%i.wad", p);
                    doom_strcpy(file.data(), "~" DEVMAPS "cdata/map");
                    doom_concat(file.data(), doom_itoa(p, 10));
                    doom_concat(file.data(), ".wad");
                }
                break;
        }
        addWadFile(file.data());
    }

    p = Doom::checkParm("-file");
    if (p)
    {
        // the parms after p are wadfile/lump names,
        // until end of parms or another - preceded parm
        version.modifiedgame = true; // homebrew levels
        while (++p != myargc && myargv[p][0] != '-')
            addWadFile(myargv[p]);
    }

    p = Doom::checkParm("-playdemo");

    if (!p)
        p = Doom::checkParm("-timedemo");

    if (p && p < myargc - 1)
    {
        //doom_sprintf(file, "%s.lmp", myargv[p + 1]);
        doom_strcpy(file.data(), myargv[p + 1]);
        doom_concat(file.data(), ".lmp");
        addWadFile(file.data());
        //doom_print("Playing demo %s.lmp.\n", myargv[p + 1]);
        doom_print("Playing demo ");
        doom_print(myargv[p + 1]);
        doom_print(".lmp.\n");
    }

    // get skill / episode / map from parms
    defaults_.startskill = sk_medium;
    defaults_.startepisode = 1;
    defaults_.startmap = 1;
    defaults_.autostart = false;

    p = Doom::checkParm("-skill");
    if (p && p < myargc - 1)
    {
        defaults_.startskill = static_cast<Skill>((myargv[p + 1][0] - '1'));
        defaults_.autostart = true;
    }

    p = Doom::checkParm("-episode");
    if (p && p < myargc - 1)
    {
        defaults_.startepisode = myargv[p + 1][0] - '0';
        defaults_.startmap = 1;
        defaults_.autostart = true;
    }

    p = Doom::checkParm("-timer");
    if (p && p < myargc - 1 && session.deathmatch)
    {
        int time = doom_atoi(myargv[p + 1]);
        //doom_print("Levels will end after %d minute", time);
        doom_print("Levels will end after ");
        doom_print(doom_itoa(time, 10));
        doom_print(" minute");
        if (time > 1)
            doom_print("s");
        doom_print(".\n");
    }

    p = Doom::checkParm("-avg");
    if (p && p < myargc - 1 && session.deathmatch)
        doom_print("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = Doom::checkParm("-warp");
    if (p && p < myargc - 1)
    {
        if (version.gamemode == commercial)
            defaults_.startmap = doom_atoi(myargv[p + 1]);
        else
        {
            defaults_.startepisode = myargv[p + 1][0] - '0';
            defaults_.startmap = myargv[p + 2][0] - '0';
        }
        defaults_.autostart = true;
    }

    // init subsystems
    doom_print("Doom::initVideo: allocate screens.\n");
    Doom::initVideo();

    doom_print("Doom::loadDefaults: Load system defaults.\n");
    Doom::loadDefaults(); // load before initing other systems

    doom_print("W_Init: Init WADfiles.\n");
    Doom::initWadFiles(wadfiles);

    // Check for -file in shareware
    if (version.modifiedgame)
    {
        // These are the lumps that will be checked in IWAD,
        // if any one is not present, execution will be aborted.
        EA::Array<const char*, 23> name = {
            "e2m1",   "e2m2",   "e2m3",   "e2m4",   "e2m5",    "e2m6",
            "e2m7",   "e2m8",   "e2m9",   "e3m1",   "e3m3",    "e3m3",
            "e3m4",   "e3m5",   "e3m6",   "e3m7",   "e3m8",    "e3m9",
            "dphoof", "bfgga0", "heada1", "cybra1", "spida1d1"};

        if (version.gamemode == shareware)
            fatalError("Error: \nYou cannot -file with the shareware "
                       "version. Register!");

        // Check for fake IWAD with right name,
        // but w/o all the lumps of the registered version.
        if (version.gamemode == registered)
            for (auto n: name)
                if (Doom::wad().find(n) < 0)
                    fatalError("Error: \nThis is not the registered version.");
    }

    // Iff additonal PWAD files are used, print modified banner
    if (version.modifiedgame)
    {
        /*m*/ doom_print(
            "===========================================================================\n"
            "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
            "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
            "        You will not receive technical support for modified games.\n"
            //"                      press enter to continue\n"
            "===========================================================================\n");
        //getchar();
    }

    // Check and print which version is executed.
    switch (version.gamemode)
    {
        case shareware:
        case indetermined:
            doom_print(
                "===========================================================================\n"
                "                                Shareware!\n"
                "===========================================================================\n");
            break;
        case registered:
        case retail:
        case commercial:
            doom_print(
                "===========================================================================\n"
                "                 Commercial product - do not distribute!\n"
                "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
                "===========================================================================\n");
            break;

        default:
            // Ouch.
            break;
    }

    doom_print("initMenu: Init miscellaneous info.\n");
    initMenu();

    doom_print("Doom::renderInit: Init DOOM refresh daemon - ");
    Doom::renderInit();

    doom_print("\nP_Init: Init Playloop state.\n");
    Doom::init();

    doom_print("initHost: Setting up machine state.\n");
    initHost();

    doom_print("Doom::checkNetGame: Checking network game status.\n");
    Doom::checkNetGame();

    doom_print("Doom::initSound: Setting up sound.\n");
    Doom::initSound(soundSettings().sfxVolume /* *8 */,
                    soundSettings().musicVolume /* *8*/);

    doom_print("Doom::initHud: Setting up heads up display.\n");
    Doom::initHud();

    doom_print("Doom::initStatusBar: Init status bar.\n");
    Doom::initStatusBar();

    // check for a driver that wants intermission stats
#if 0 // [pd] Unsure how to test this
    p = Doom::checkParm("-statcopy");
    if (p && p < myargc - 1)
    {
        // for statistics driver
        statcopy = (void*)atoll(myargv[p + 1]);
        doom_print("External statistics registered.\n");
    }
#endif

    // start the apropriate game based on parms
    p = Doom::checkParm("-record");

    if (p && p < myargc - 1)
    {
        Doom::recordDemo(myargv[p + 1]);
        defaults_.autostart = true;
    }

    p = Doom::checkParm("-playdemo");
    if (p && p < myargc - 1)
    {
        demoState().singledemo = true; // quit after one demo
        Doom::deferPlayDemo(myargv[p + 1]);
        doomLoop(); // never returns
    }

    p = Doom::checkParm("-timedemo");
    if (p && p < myargc - 1)
    {
        Doom::startTimeDemo(myargv[p + 1]);
        doomLoop(); // never returns
    }

    p = Doom::checkParm("-loadgame");
    if (p && p < myargc - 1)
    {
#if 0 // [pd] We don't support the cdrom flag
        if (Doom::checkParm("-cdrom"))
        {
            //doom_sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg", myargv[p + 1][0]);
        }
        else
#endif
        {
            //doom_sprintf(file, SAVEGAMENAME"%c.dsg", myargv[p + 1][0]);
            doom_strcpy(file.data(), SAVEGAMENAME);
            doom_concat(file.data(), doom_ctoa(myargv[p + 1][0]));
            doom_concat(file.data(), ".dsg");
        }
        Doom::loadGame(file.data());
    }

    if (gameFlow().gameaction != ga_loadgame)
    {
        if (defaults_.autostart || session.netgame)
            Doom::initNewGame(
                defaults_.startskill, defaults_.startepisode, defaults_.startmap);
        else
            startTitle(); // start up intro loop
    }

    // doomLoop (); // never returns [ddps] Called by app

    if (demoState().demorecording)
        Doom::beginRecording();

    if (Doom::checkParm("-debugfile"))
    {
        EA::Array<char, 20> filename;
        //doom_sprintf(filename, "debug%i.txt", consoleplayer);
        doom_strcpy(filename.data(), "debug");
        doom_concat(filename.data(), doom_itoa(playerState().consoleplayer, 10));
        doom_concat(filename.data(), ".txt");
        //doom_print("debug output to: %s\n", filename);
        doom_print("debug output to: ");
        doom_print(filename.data());
        doom_print("\n");
        engineParams().debugfile = doom_open(filename.data(), "w");
    }

    initGraphics();
}

} // namespace Doom
