// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//        DOOM main program (doomMain) and game loop (doomLoop),
//        plus functions to determine game mode (shareware, registered),
//        parse command line parameters, configure game parameters (turbo),
//        and call the startup functions.
//
//-----------------------------------------------------------------------------

#include "../Host/Platform.h"

#include "GameDefs.h"
#include "MapSpawns.h"
#include "Strings.h"
#include "SoundData.h"
#include "../Wad/WadFile.h"
#include "../UI/Wipe.h"
#include "Args.h"
#include "ConfigTypes.h"
#include "../UI/Menu.h"
#include "../UI/Hud.h"
#include "../UI/IntermissionTypes.h"
#include "../UI/StatusBarTypes.h"
#include "../UI/AutomapTypes.h"
#include "DoomMain.h"

#include "AttractMode.h"
#include "DoomMain.h"
#include "ConfigPaths.h"

#include "../Containers.h"
#include "DemoState.h"
#include "DisplayState.h"
#include "EngineParams.h"
#include "EventQueue.h"
#include "GameClock.h"
#include "GameFlow.h"
#include "GameSession.h"
#include "GameVersion.h"
#include "LaunchOptions.h"
#include "MovementSpeeds.h"
#include "NetState.h"
#include "PlayerState.h"
#include "RefreshFlags.h"
#include "SoundSettings.h"
#include "StartupDefaults.h"

#include "../Render/Draw.h"
#include "../Render/Video.h"
#include "../Sim/Setup.h"
#include "../UI/Automap.h"
#include "../UI/Finale.h"
#include "../UI/Hud.h"
#include "../UI/Intermission.h"
#include "../UI/StatusBar.h"
#include "../UI/Wipe.h"
#include "Args.h"
#include "Config.h"
#include "Net.h"
#include "../Host/Sound.h"
#include "../UI/Menu.h"
#include "../Host/Video.h"
#include "../Host/System.h"
#include "../Game/OverlayState.h"
#include "../Render/Main.h"
#include "../Render/ViewWindow.h"
#include "Game.h"
#include "Sound.h"

// The boot-time WAD list, file-local: Doom::addWadFile appends to it and Doom::initWadFiles
// consumes it, and nothing outside this file reads it (its d_main.h extern is gone).
static Doom::Vector<std::string> wadfiles;

// The command-line launch flags are a Doom::LaunchOptions owned by the Engine now; these
// are references onto it (REFACTOR.md, Step 5).

// (drone, an always-unread vestige, was deleted here - the Doom::DoomCom.drone in d_net.h
// is an unrelated struct member.)

// singletics / debugfile are Doom::EngineParams owned by the Engine now; these are references onto
// it (REFACTOR.md, Step 5).

// The new-game defaults are a Doom::StartupDefaults owned by the Engine now; these are
// references onto it (REFACTOR.md, Step 5).

// advancedemo is a Doom::AttractMode member owned by the Engine now; this reference stays
// because d_main.h still externs it for Tests/SimProbe (REFACTOR.md, Step 5). Its
// demosequence/pagetic siblings had no reader outside this file and are gone; pagename's
// reference is below, kept for g_game.

// wadfile[]/mapdir[] were dead (referenced only in comments) and are deleted, the
// linecount/loopcount/viewangleoffset way. basedefault is an Engine member now
// (Game/ConfigPaths.h) - it was never actually config-blocked, since defaults[] does
// not capture its address (defaultfile is assigned it at runtime, not bound to it).

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
// The input event ring buffer is a Doom::EventQueue owned by the Engine now; these vanilla
// names are references onto it (events[] as a reference-to-array).

// wipegamestate (with gamestate) is a Doom::GameFlow owned by the Engine now; this is a
// reference onto it. It can be set to -1 to force a wipe on the next draw.
void Doom::executeSetViewSize();

// Title/demo-loop state: a member of the Doom::AttractMode above, still read by g_game
// through its own extern declaration.

// Other subsystems' globals/functions this file reaches (at global scope so the
// namespace code below binds :: not Doom::).
// statcopy is a ::-scope accessor (Game/Game.cpp); no header declares it, so
// this file forward-declares it.
void*& statcopy();
void Doom::checkNetGame();
void Doom::buildTiccmd(Doom::Ticcmd& cmd);

namespace Doom
{

// Forward declarations so call order needs no rearranging.
void doomLoop();
void processEvents();
void doAdvanceDemo();

//
// postEvent
// Called by the I/O functions when input is detected
//
void postEvent(Event& ev)
{
    auto& events_ = eventQueue();

    events_.events[events_.eventhead] = ev;
    events_.eventhead++;
    events_.eventhead = (events_.eventhead) & (MAXEVENTS - 1);
}

//
// processEvents
// Send all the events of the given timestamp down the responder chain
//
void processEvents()
{
    Event* ev;

    auto& events_ = eventQueue();

    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ((gameVersion().gamemode == GameMode::Commercial)
        && (wad().find("map01") < 0))
        return;

    for (; events_.eventtail != events_.eventhead;)
    {
        ev = &events_.events[events_.eventtail];
        if (!menuResponder(*ev))
            gameResponder(*ev);
        // else menu ate the event
        events_.eventtail++;
        events_.eventtail = (events_.eventtail) & (MAXEVENTS - 1);
    }
}

//
// displayFrame
//  draw current display, possibly wiping it from the previous
//
void displayFrame()
{
    auto& view = viewWindow();
    auto& overlay = overlayState();

    // The frame-diff state machine: a DisplayState owned by the Engine now, reached by local
    // references (formerly displayFrame's own function-local statics, never reset - identical
    // persistence).
    DisplayState& ds = displayState();
    bool& viewactivestate = ds.viewactivestate;
    bool& menuactivestate = ds.menuactivestate;
    bool& inhelpscreensstate = ds.inhelpscreensstate;
    bool& fullscreen = ds.fullscreen;
    GameState& oldgamestate = ds.oldgamestate;
    int& borderdrawcount = ds.borderdrawcount;
    int y;
    bool wipe;
    bool redrawsbar;

    auto& flow = gameFlow();
    auto& clock = gameClock();
    auto& refresh = refreshFlags();

    if (refresh.nodrawers)
        return; // for comparative timing / profiling

    redrawsbar = false;

    // change the view size if needed
    if (view.setsizeneeded)
    {
        executeSetViewSize();
        oldgamestate = GS_FORCE_WIPE; // force background redraw
        borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (flow.gamestate != flow.wipegamestate)
    {
        wipe = true;
        startScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
        wipe = false;

    if (flow.gamestate == GameState::Level && clock.gametic)
        eraseHud();

    // do buffered drawing
    switch (flow.gamestate)
    {
        case GameState::Level:
            if (!clock.gametic)
                break;
            if (overlay.automapactive)
                drawAutomap();
            if (wipe || (view.viewheight != 200 && fullscreen))
                redrawsbar = true;
            if (inhelpscreensstate && !overlay.inhelpscreens)
                redrawsbar = true; // just put away the help screen
            drawStatusBar(view.viewheight == 200, redrawsbar);
            fullscreen = view.viewheight == 200;
            break;

        case GameState::Intermission:
            drawIntermission();
            break;

        case GameState::Finale:
            drawFinale();
            break;

        case GameState::DemoScreen:
            drawPage();
            break;
    }

    // draw buffered stuff to screen
    updateNoBlit();

    // draw the view directly
    if (flow.gamestate == GameState::Level && !overlay.automapactive
        && clock.gametic)
    {
        auto& state = playerState();
        renderPlayerView(state.players[state.displayplayer]);
    }

    if (flow.gamestate == GameState::Level && clock.gametic)
        drawHud();

    // clean up border stuff
    if (flow.gamestate != oldgamestate && flow.gamestate != GameState::Level)
        setPalette(static_cast<byte*>((cacheLumpName("PLAYPAL"))));

    // see if the border needs to be initially drawn
    if (flow.gamestate == GameState::Level && oldgamestate != GameState::Level)
    {
        viewactivestate = false; // view was not active
        fillBackScreen(); // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (flow.gamestate == GameState::Level && !overlay.automapactive
        && view.scaledviewwidth != 320)
    {
        if (overlay.menuactive || menuactivestate || !viewactivestate)
            borderdrawcount = 3;
        if (borderdrawcount)
        {
            drawViewBorder(); // erase old menu stuff
            borderdrawcount--;
        }
    }

    menuactivestate = overlay.menuactive;
    viewactivestate = refresh.viewactive;
    inhelpscreensstate = overlay.inhelpscreens;
    oldgamestate = flow.wipegamestate = flow.gamestate;

    // draw pause pic
    if (refresh.paused)
    {
        if (overlay.automapactive)
            y = 4;
        else
            y = view.viewwindowy + 4;
        drawPatchDirect(view.viewwindowx + (view.scaledviewwidth - 68) / 2,
                        y,
                        0,
                        static_cast<Patch*>((cacheLumpName("M_PAUSE"))));
    }

    // menus go directly to the screen
    drawMenu(); // menu is drawn even on top of everything
    netUpdate(); // send out any new accumulation

    // normal update
    flow.is_wiping_screen = wipe;
    if (!wipe)
    {
        finishUpdate(); // page flip or blit buffer
        return;
    }

    // wipe update
    endScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

#if 0 // [pd] Moved to updateWipe
    do
    {
        do
        {
            nowtime = currentTic();
            tics = nowtime - wipestart;
        } while (!tics);
        wipestart = nowtime;
        done = screenWipe(WipeType::Melt
                               , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
        updateNoBlit();
        drawMenu();                            // menu is drawn even on top of wipes
        finishUpdate();                      // page flip or blit buffer
    } while (!done);
#endif
}

//
//  doomLoop
//
void updateWipe()
{
    if (screenWipe(WipeType::Melt, 0, 0, SCREENWIDTH, SCREENHEIGHT, 1))
        gameFlow().is_wiping_screen = false;
}

void doomLoop()
{
#if 0 // [pd] Moved to doomMain()
    if (demorecording)
        beginRecording();

    if (checkParm("-debugfile"))
    {
        Array<char, 20> filename;
        //doom_sprintf(filename, "debug%i.txt", consoleplayer);
        doom_print("debug output to: %s\n", filename.data());
        debugfile = doom_open(filename.data(), "w");
    }

    initGraphics();
#endif

    auto& state = playerState();

    // while (1)
    {
        // frame syncronous IO operations
        startFrame();

        // process one or more tics
        if (engineParams().singletics)
        {
            auto& net = netState();
            auto& clock = gameClock();

            startTic();
            processEvents();
            buildTiccmd(net.netcmds[state.consoleplayer][net.maketic % BACKUPTICS]);
            if (attractMode().advancedemo)
                doAdvanceDemo();
            menuTicker();
            gameTicker();
            clock.gametic++;
            net.maketic++;
        }
        else
        {
            tryRunTics(); // will run at least one tic
        }

        // move positional sounds
        updateSounds(state.players[state.consoleplayer].mo);

        // Update display, next frame, with current state.
        displayFrame();

#if 0 // [pd] Sound is queried by the application's audio thread.
        // Sound mixing for the buffer is snychronous.
        updateSound();

        // Synchronous sound output is explicitly called.
        // Update sound output.
        submitSound();
#endif
    }
}

//
//  DEMO LOOP
//

//
// pageTicker
// Handles timing for warped projection
//
void pageTicker()
{
    if (--attractMode().pagetic < 0)
        advanceDemo();
}

//
// drawPage
//
void drawPage()
{
    drawPatch(0, 0, 0, static_cast<Patch*>((cacheLumpName(attractMode().pagename))));
}

//
// advanceDemo
// Called after each demo or intro demosequence finishes
//
void advanceDemo()
{
    attractMode().advancedemo = true;
}

//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
void doAdvanceDemo()
{
    auto& state = playerState();
    auto& attract = attractMode();
    auto& flow = gameFlow();
    const GameMode gamemode = gameVersion().gamemode;

    state.players[state.consoleplayer].playerstate =
        PlayerLifeState::Live; // not reborn
    attract.advancedemo = false;
    demoState().usergame = false; // no save / end game here
    refreshFlags().paused = false;
    flow.gameaction = GameAction::Nothing;

    if (gamemode == GameMode::Retail)
        attract.demosequence = (attract.demosequence + 1) % 7;
    else
        attract.demosequence = (attract.demosequence + 1) % 6;

    switch (attract.demosequence)
    {
        case 0:
            if (gamemode == GameMode::Commercial)
                attract.pagetic = 35 * 11;
            else
                attract.pagetic = 170;
            flow.gamestate = GameState::DemoScreen;
            attract.pagename = "TITLEPIC";
            if (gamemode == GameMode::Commercial)
                startMusic(MusicEnum::Dm2ttl);
            else
                startMusic(MusicEnum::Intro);
            break;
        case 1:
            deferPlayDemo("demo1");
            break;
        case 2:
            attract.pagetic = 200;
            flow.gamestate = GameState::DemoScreen;
            attract.pagename = "CREDIT";
            break;
        case 3:
            deferPlayDemo("demo2");
            break;
        case 4:
            flow.gamestate = GameState::DemoScreen;
            if (gamemode == GameMode::Commercial)
            {
                attract.pagetic = 35 * 11;
                attract.pagename = "TITLEPIC";
                startMusic(MusicEnum::Dm2ttl);
            }
            else
            {
                attract.pagetic = 200;

                if (gamemode == GameMode::Retail)
                    attract.pagename = "CREDIT";
                else
                    attract.pagename = "HELP2";
            }
            break;
        case 5:
            deferPlayDemo("demo3");
            break;
            // THE DEFINITIVE DOOM Special Edition demo
        case 6:
            deferPlayDemo("demo4");
            break;
    }
}

//
// startTitle
//
void startTitle()
{
    gameFlow().gameaction = GameAction::Nothing;
    attractMode().demosequence = -1;
    advanceDemo();
}

//
// addWadFile
//
void addWadFile(std::string_view file)
{
    wadfiles.push_back(std::string {file});
}

// Joins the WAD directory and a leading-slash basename into one owned string.
// The point of it is that the size comes from the two strings themselves rather
// than from a number written beside them - see the note at the call sites, where
// one of seven such numbers was wrong and overflowed the buffer by a byte.
static std::string joinWadPath(std::string_view directory, std::string_view file)
{
    return concat(directory, file);
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion()
{
    auto& version = gameVersion();
    auto& opts = launchOptions();
    auto& paths = configPaths();

    auto doomwaddir = host().getenv("DOOMWADDIR").value_or(".");

    // Each of these was sized by hand, as `strlen(dir) + 1 + <basename> + 1`
    // with the basename's length written out as a literal - and one of the seven
    // had it wrong. "doomu.wad" is nine characters and was counted as eight, so
    // building the retail path wrote its terminating NUL one byte past the
    // allocation, every single boot.
    //
    // It went unseen because it depends entirely on what the allocator puts
    // there: on macOS the block's own padding absorbed it, while on Windows
    // arm64 it corrupted the following block and demo1 and demo3 died with a
    // segfault before rendering a frame. AddressSanitizer names it in one line.
    // Nothing above the allocator could see it - the goldens hash the world and
    // the picture, and both were correct right up until the heap gave out.
    //
    // So the literal is gone rather than corrected: joinWadPath measures the
    // string it is about to write, which is the only count that cannot disagree
    // with it.
    const auto doom2wad = joinWadPath(doomwaddir, "/doom2.wad"); // Commercial.
    const auto doomuwad = joinWadPath(doomwaddir, "/doomu.wad"); // Retail.
    const auto doomwad = joinWadPath(doomwaddir, "/doom.wad"); // Registered.
    const auto doom1wad = joinWadPath(doomwaddir, "/doom1.wad"); // Shareware.
    const auto plutoniawad = joinWadPath(doomwaddir, "/plutonia.wad");
    const auto tntwad = joinWadPath(doomwaddir, "/tnt.wad");
    const auto doom2fwad = joinWadPath(doomwaddir, "/doom2f.wad"); // French.

#if !defined(DOOM_WIN32)
    auto home = host().getenv("HOME");
    if (!home)
        fatalError("Error: Please set $HOME to your home directory");
#else
    auto home = std::optional<std::string> {"."};
#endif
    //doom_sprintf(basedefault, "%s/.doomrc", home);
    paths.basedefault = concat(*home, "/.doomrc");

    if (checkParm("-shdev"))
    {
        version.gamemode = GameMode::Shareware;
        opts.devparm = true;
        addWadFile(DEVDATA "doom1.wad");
        addWadFile(DEVMAPS "data_se/texture1.lmp");
        addWadFile(DEVMAPS "data_se/pnames.lmp");
        paths.basedefault = DEVDATA "default.cfg";
        return;
    }

    if (checkParm("-regdev"))
    {
        version.gamemode = GameMode::Registered;
        opts.devparm = true;
        addWadFile(DEVDATA "doom.wad");
        addWadFile(DEVMAPS "data_se/texture1.lmp");
        addWadFile(DEVMAPS "data_se/texture2.lmp");
        addWadFile(DEVMAPS "data_se/pnames.lmp");
        paths.basedefault = DEVDATA "default.cfg";
        return;
    }

    if (checkParm("-comdev"))
    {
        version.gamemode = GameMode::Commercial;
        opts.devparm = true;
        /* I don't bother
        if(plutonia)
            addWadFile (DEVDATA"plutonia.wad");
        else if(tnt)
            addWadFile (DEVDATA"tnt.wad");
        else*/
        addWadFile(DEVDATA "doom2.wad");

        addWadFile(DEVMAPS "cdata/texture1.lmp");
        addWadFile(DEVMAPS "cdata/pnames.lmp");
        paths.basedefault = DEVDATA "default.cfg";
        return;
    }

    void* f;
    if ((f = host().open(doom2fwad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Commercial;
        // C'est ridicule!
        // Let's handle languages in config files, okay?
        version.language = Language::French;
        print("French version\n");
        addWadFile(doom2fwad);
        return;
    }

    if ((f = host().open(doom2wad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Commercial;
        addWadFile(doom2wad);
        return;
    }

    if ((f = host().open(plutoniawad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Commercial;
        addWadFile(plutoniawad);
        return;
    }

    if ((f = host().open(tntwad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Commercial;
        addWadFile(tntwad);
        return;
    }

    if ((f = host().open(doomuwad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Retail;
        addWadFile(doomuwad);
        return;
    }

    if ((f = host().open(doomwad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Registered;
        addWadFile(doomwad);
        return;
    }

    if ((f = host().open(doom1wad.c_str(), "rb")))
    {
        host().close(f);
        version.gamemode = GameMode::Shareware;
        addWadFile(doom1wad);
        return;
    }

    print("Game mode indeterminate.\n");
    version.gamemode = GameMode::Indetermined;
}

//
// Find a Response File
//
void findResponseFile()
{
    for (int i = 1; i < myargCount(); i++)
    {
        if (myargv()[i][0] != '@')
            continue;

        auto responseFile = myargv()[i].substr(1);

        // READ THE RESPONSE FILE INTO MEMORY
        auto* handle = host().open(responseFile, "rb");

        if (!handle)
        {
            print("\nNo such response file!");
            host().exit(1);
        }

        print("Found response file ", responseFile, "!\n");

        host().seek(handle, 0, SeekOrigin::End);
        auto size = host().tell(handle);
        host().seek(handle, 0, SeekOrigin::Set);

        auto contents = std::string(static_cast<std::size_t>(size), '\0');
        host().read(handle, contents.data(), size);
        host().close(handle);

        // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
        auto moreargs =
            std::vector<std::string>(myargv().begin() + i + 1, myargv().end());

        auto rebuilt = std::vector<std::string> {myargv()[0]}; // KEEP ARGV[0]

        // Tokenised on vanilla's own character class: a token runs while the byte
        // is above ' ' and not past 'z', and the run of anything else between
        // tokens is skipped. An empty leading token is kept, as it was.
        auto k = 0;

        while (k < size)
        {
            auto start = k;

            while (k < size && contents[k] >= ' ' + 1 && contents[k] <= 'z')
                k++;

            rebuilt.emplace_back(contents, start, k - start);

            while (k < size && (contents[k] <= ' ' || contents[k] > 'z'))
                k++;
        }

        rebuilt.insert(rebuilt.end(), moreargs.begin(), moreargs.end());
        myargv() = std::move(rebuilt);

        // DISPLAY ARGS
        print(myargCount(), " command-line args:\n");

        for (auto arg = 1; arg < myargCount(); arg++)
            print(myargv()[arg], "\n");

        break;
    }
}

//
// doomMain
//
void doomMain()
{
    int p;
    auto file = std::string {};

    auto& version = gameVersion();
    auto& opts = launchOptions();
    auto& session = gameSession();
    auto& defaults_ = startupDefaults();

    findResponseFile();

    IdentifyVersion();

    version.modifiedgame = false;

    opts.nomonsters = checkParm("-nomonsters");
    opts.respawnparm = checkParm("-respawn");
    opts.fastparm = checkParm("-fast");
    opts.devparm = checkParm("-devparm");
    if (checkParm("-altdeath"))
        session.deathmatch = 2;
    else if (checkParm("-deathmatch"))
        session.deathmatch = 1;

    auto title = std::string {};

    switch (version.gamemode)
    {
        case GameMode::Retail:
            title = concat("                         "
                           "The Ultimate DOOM Startup v",
                           VERSION / 100,
                           ".",
                           VERSION % 100,
                           "                           ");
            break;
        case GameMode::Shareware:
            title = concat("                            "
                           "DOOM Shareware Startup v",
                           VERSION / 100,
                           ".",
                           VERSION % 100,
                           "                           ");
            break;
        case GameMode::Registered:
            title = concat("                            "
                           "DOOM Registered Startup v",
                           VERSION / 100,
                           ".",
                           VERSION % 100,
                           "                           ");
            break;
        case GameMode::Commercial:
            title = concat("                         "
                           "DOOM 2: Hell on Earth v",
                           VERSION / 100,
                           ".",
                           VERSION % 100,
                           "                           ");
            break;
            /*FIXME
                   case pack_plut:
                    sprintf (title,
                             "                   "
                             "DOOM 2: Plutonia Experiment v%i.%i"
                             "                           ",
                             VERSION/100,VERSION%100);
                    break;
                  case pack_tnt:
                    sprintf (title,
                             "                     "
                             "DOOM 2: TNT - Evilution v%i.%i"
                             "                           ",
                             VERSION/100,VERSION%100);
                    break;
            */
        case GameMode::Indetermined:
            title = concat("                     "
                           "Public DOOM - v",
                           VERSION / 100,
                           ".",
                           VERSION % 100,
                           "                           ");
            break;
    }

    print(title, "\n");

    if (opts.devparm)
        print(D_DEVSTR);

#if 0 // [pd] Ignore cdrom
    if (checkParm("-cdrom"))
    {
        doom_print(D_CDROM);
        mkdir("c:\\doomdata", 0);
        doom_strcpy(basedefault, "c:/doomdata/default.cfg");
    }
#endif

    // turbo option
    if ((p = checkParm("-turbo")))
    {
        int scale = 200;

        if (p < myargCount() - 1)
            scale = parseInt(myargv()[p + 1]);
        if (scale < 10)
            scale = 10;
        if (scale > 400)
            scale = 400;
        //doom_print("turbo scale: %i%%\n", scale);
        print("turbo scale: ", scale, "%%\n");

        auto& speeds = movementSpeeds();
        speeds.forwardmove[0] = speeds.forwardmove[0] * scale / 100;
        speeds.forwardmove[1] = speeds.forwardmove[1] * scale / 100;
        speeds.sidemove[0] = speeds.sidemove[0] * scale / 100;
        speeds.sidemove[1] = speeds.sidemove[1] * scale / 100;
    }

    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = checkParm("-wart");
    if (p)
    {
        myargv()[p][4] = 'p'; // big hack, change to -warp

        // Map name handling.
        switch (version.gamemode)
        {
            case GameMode::Shareware:
            case GameMode::Retail:
            case GameMode::Registered:
                file = concat("~" DEVMAPS "E",
                              myargv()[p + 1][0],
                              "M",
                              myargv()[p + 2][0],
                              ".wad");

                print("Warping to Episode ",
                      myargv()[p + 1],
                      ", Map ",
                      myargv()[p + 2],
                      ".\n");
                break;

            case GameMode::Commercial:
            case GameMode::Indetermined:
                p = parseInt(myargv()[p + 1]);
                if (p < 10)
                    file = concat("~" DEVMAPS "cdata/map0", p, ".wad");
                else
                    file = concat("~" DEVMAPS "cdata/map", p, ".wad");
                break;
        }
        addWadFile(file.c_str());
    }

    p = checkParm("-file");
    if (p)
    {
        // the parms after p are wadfile/lump names,
        // until end of parms or another - preceded parm
        version.modifiedgame = true; // homebrew levels
        while (++p != myargCount() && myargv()[p][0] != '-')
            addWadFile(myargv()[p]);
    }

    p = checkParm("-playdemo");

    if (!p)
        p = checkParm("-timedemo");

    if (p && p < myargCount() - 1)
    {
        file = concat(myargv()[p + 1], ".lmp");
        addWadFile(file.c_str());
        //doom_print("Playing demo %s.lmp.\n", myargv[p + 1]);
        print("Playing demo ", myargv()[p + 1], ".lmp.\n");
    }

    // get skill / episode / map from parms
    defaults_.startskill = Skill::Medium;
    defaults_.startepisode = 1;
    defaults_.startmap = 1;
    defaults_.autostart = false;

    p = checkParm("-skill");
    if (p && p < myargCount() - 1)
    {
        defaults_.startskill = static_cast<Skill>((myargv()[p + 1][0] - '1'));
        defaults_.autostart = true;
    }

    p = checkParm("-episode");
    if (p && p < myargCount() - 1)
    {
        defaults_.startepisode = myargv()[p + 1][0] - '0';
        defaults_.startmap = 1;
        defaults_.autostart = true;
    }

    p = checkParm("-timer");
    if (p && p < myargCount() - 1 && session.deathmatch)
    {
        int time = parseInt(myargv()[p + 1]);
        //doom_print("Levels will end after %d minute", time);
        print("Levels will end after ", time, " minute");
        if (time > 1)
            print("s");
        print(".\n");
    }

    p = checkParm("-avg");
    if (p && p < myargCount() - 1 && session.deathmatch)
        host().print("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = checkParm("-warp");
    if (p && p < myargCount() - 1)
    {
        if (version.gamemode == GameMode::Commercial)
            defaults_.startmap = parseInt(myargv()[p + 1]);
        else
        {
            defaults_.startepisode = myargv()[p + 1][0] - '0';
            defaults_.startmap = myargv()[p + 2][0] - '0';
        }
        defaults_.autostart = true;
    }

    // init subsystems
    // (The video screens are allocated by VideoState's constructor now, not a boot
    // step - see Render/VideoState.h.)
    host().print("loadDefaults: Load system defaults.\n");
    loadDefaults(); // load before initing other systems

    host().print("W_Init: Init WADfiles.\n");
    initWadFiles(wadfiles);

    // Check for -file in shareware
    if (version.modifiedgame)
    {
        // These are the lumps that will be checked in IWAD,
        // if any one is not present, execution will be aborted.
        Array<std::string_view, 23> name = {
            "e2m1",   "e2m2",   "e2m3",   "e2m4",   "e2m5",    "e2m6",
            "e2m7",   "e2m8",   "e2m9",   "e3m1",   "e3m3",    "e3m3",
            "e3m4",   "e3m5",   "e3m6",   "e3m7",   "e3m8",    "e3m9",
            "dphoof", "bfgga0", "heada1", "cybra1", "spida1d1"};

        if (version.gamemode == GameMode::Shareware)
            fatalError("Error: \nYou cannot -file with the shareware "
                       "version. Register!");

        // Check for fake IWAD with right name,
        // but w/o all the lumps of the registered version.
        if (version.gamemode == GameMode::Registered)
            for (auto n: name)
                if (wad().find(n) < 0)
                    fatalError("Error: \nThis is not the registered version.");
    }

    // Iff additonal PWAD files are used, print modified banner
    if (version.modifiedgame)
    {
        /*m*/ host().print(
            "===========================================================================\n"
            "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
            "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
            "        You will not receive technical support for modified games.\n"
            //"                      press enter to continue\n"
            "===========================================================================\n");
        //getchar();
    }

    // Check and print which version is executed.
    switch (version.gamemode)
    {
        case GameMode::Shareware:
        case GameMode::Indetermined:
            host().print(
                "===========================================================================\n"
                "                                Shareware!\n"
                "===========================================================================\n");
            break;
        case GameMode::Registered:
        case GameMode::Retail:
        case GameMode::Commercial:
            host().print(
                "===========================================================================\n"
                "                 Commercial product - do not distribute!\n"
                "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
                "===========================================================================\n");
            break;

            // Vanilla's trailing `default: // Ouch.` was already unreachable here -
            // Indetermined is handled with Shareware above, so all five modes are
            // covered. Making the switch exhaustive is what made that visible.
    }

    host().print("initMenu: Init miscellaneous info.\n");
    initMenu();

    host().print("renderInit: Init DOOM refresh daemon - ");
    renderInit();

    host().print("\nP_Init: Init Playloop state.\n");
    init();

    host().print("initHost: Setting up machine state.\n");
    initHost();

    host().print("checkNetGame: Checking network game status.\n");
    checkNetGame();

    host().print("initSound: Setting up sound.\n");
    initSound(soundSettings().sfxVolume /* *8 */,
              soundSettings().musicVolume /* *8*/);

    host().print("initHud: Setting up heads up display.\n");
    initHud();

    host().print("initStatusBar: Init status bar.\n");
    initStatusBar();

    // check for a driver that wants intermission stats
#if 0 // [pd] Unsure how to test this
    p = checkParm("-statcopy");
    if (p && p < myargCount() - 1)
    {
        // for statistics driver
        statcopy() = (void*)atoll(myargv()[p + 1].c_str());
        doom_print("External statistics registered.\n");
    }
#endif

    // start the apropriate game based on parms
    p = checkParm("-record");

    if (p && p < myargCount() - 1)
    {
        recordDemo(myargv()[p + 1]);
        defaults_.autostart = true;
    }

    p = checkParm("-playdemo");
    if (p && p < myargCount() - 1)
    {
        demoState().singledemo = true; // quit after one demo
        deferPlayDemo(myargv()[p + 1]);
        doomLoop(); // never returns
    }

    p = checkParm("-timedemo");
    if (p && p < myargCount() - 1)
    {
        startTimeDemo(myargv()[p + 1]);
        doomLoop(); // never returns
    }

    p = checkParm("-loadgame");
    if (p && p < myargCount() - 1)
    {
#if 0 // [pd] We don't support the cdrom flag
        if (checkParm("-cdrom"))
        {
            //doom_sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg", myargv[p + 1][0]);
        }
        else
#endif
        {
            //doom_sprintf(file, SAVEGAMENAME"%c.dsg", myargv[p + 1][0]);
            file = concat(SAVEGAMENAME, myargv()[p + 1][0], ".dsg");
        }
        loadGame(file.c_str());
    }

    if (gameFlow().gameaction != GameAction::LoadGame)
    {
        if (defaults_.autostart || session.netgame)
            initNewGame(
                defaults_.startskill, defaults_.startepisode, defaults_.startmap);
        else
            startTitle(); // start up intro loop
    }

    // doomLoop (); // never returns [ddps] Called by app

    if (demoState().demorecording)
        beginRecording();

    if (checkParm("-debugfile"))
    {
        //doom_sprintf(filename, "debug%i.txt", consoleplayer);
        auto filename = concat("debug", playerState().consoleplayer, ".txt");
        //doom_print("debug output to: %s\n", filename);
        print("debug output to: ", filename, "\n");
        engineParams().debugfile = host().open(filename.c_str(), "w");
    }

    initGraphics();
}

} // namespace Doom
