// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//  all external data is defined here
//  most of the data is loaded into different structures at run time
//  some internal structures shared by many modules are here
//
//-----------------------------------------------------------------------------

#pragma once

// The most basic types we use, portability.
#include "../doomtype.h"

// Some global defines, that configure the game.
#include "../Game/GameDefs.h"

//
// Map level types.
// The following data structures define the persistent format
// used in the lumps of the WAD files.
//

// Lump order in a map WAD: each map needs a couple of lumps
// to provide a complete scene geometry description.
// Offsets from the map's label lump, not a type - they are only ever added to a
// lump number. Constants for the same reason the box indices are.
constexpr int mapLumpLabel = 0; // A separator, name, ExMx or MAPxx
constexpr int mapLumpThings = 1; // Monsters, items..
constexpr int mapLumpLinedefs = 2; // LineDefs, from editing
constexpr int mapLumpSidedefs = 3; // SideDefs, from editing
constexpr int mapLumpVertexes = 4; // Vertices, edited and BSP splits generated
constexpr int mapLumpSegs = 5; // LineSegs, from LineDefs split by BSP
constexpr int mapLumpSsectors = 6; // SubSectors, list of LineSegs
constexpr int mapLumpNodes = 7; // BSP nodes
constexpr int mapLumpSectors = 8; // Sectors, from editing
constexpr int mapLumpReject = 9; // LUT, sector-sector visibility
constexpr int mapLumpBlockmap = 10; // LUT, motion clipping, walls/grid element

// A single Doom::Vertex.
namespace Doom
{
struct MapVertex
{
    short x;
    short y;
};
} // namespace Doom

// A SideDef, defining the visual appearance of a wall,
// by setting textures and offsets.
namespace Doom
{
struct MapSidedef
{
    short textureoffset;
    short rowoffset;
    char toptexture[8];
    char bottomtexture[8];
    char midtexture[8];
    // Front sector, towards viewer.
    short sector;
};
} // namespace Doom

// A LineDef, as used for editing, and as input
// to the BSP builder.
namespace Doom
{
struct MapLinedef
{
    short v1;
    short v2;
    short flags;
    short special;
    short tag;
    // sidenum[1] will be -1 if one sided
    short sidenum[2];
};
} // namespace Doom

//
// LineDef attributes.
//

// Solid, is an obstacle.
namespace Doom
{
constexpr int ML_BLOCKING = 1;
} // namespace Doom

// Blocks monsters only.
namespace Doom
{
constexpr int ML_BLOCKMONSTERS = 2;
} // namespace Doom

// Backside will not be present at all
//  if not two sided.
namespace Doom
{
constexpr int ML_TWOSIDED = 4;
} // namespace Doom

// If a texture is pegged, the texture will have
// the end exposed to air held constant at the
// top or bottom of the texture (stairs or pulled
// down things) and will move with a height change
// of one of the neighbor sectors.
// Unpegged textures allways have the first row of
// the texture at the top pixel of the line for both
// top and bottom textures (use next to windows).

// upper texture unpegged
namespace Doom
{
constexpr int ML_DONTPEGTOP = 8;
} // namespace Doom

// lower texture unpegged
namespace Doom
{
constexpr int ML_DONTPEGBOTTOM = 16;
} // namespace Doom

// In AutoMap: don't map as two sided: IT'S A SECRET!
namespace Doom
{
constexpr int ML_SECRET = 32;
} // namespace Doom

// Sound rendering: don't let sound cross two of these.
namespace Doom
{
constexpr int ML_SOUNDBLOCK = 64;
} // namespace Doom

// Don't draw on the automap at all.
namespace Doom
{
constexpr int ML_DONTDRAW = 128;
} // namespace Doom

// Set if already seen, thus drawn in automap.
namespace Doom
{
constexpr int ML_MAPPED = 256;
} // namespace Doom

// Doom::Sector definition, from editing.
namespace Doom
{
struct MapSector
{
    short floorheight;
    short ceilingheight;
    char floorpic[8];
    char ceilingpic[8];
    short lightlevel;
    short special;
    short tag;
};
} // namespace Doom

// Doom::SubSector, as generated by BSP.
namespace Doom
{
struct MapSubsector
{
    short numsegs;
    // Index of first one, segs are stored sequentially.
    short firstseg;
};
} // namespace Doom

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
namespace Doom
{
struct MapSeg
{
    short v1;
    short v2;
    short angle;
    short linedef;
    short side;
    short offset;
};
} // namespace Doom

//
// BSP node structure.
//

// Indicate a leaf.
namespace Doom
{
constexpr int NF_SUBSECTOR = 0x8000;
} // namespace Doom

namespace Doom
{
struct MapNode
{
    // Partition line from (x,y) to x+dx,y+dy)
    short x;
    short y;
    short dx;
    short dy;

    // Bounding box for each child,
    // clip against view frustum.
    short bbox[2][4];

    // If NF_SUBSECTOR its a subsector,
    // else it's a node of another subtree.
    unsigned short children[2];
};
} // namespace Doom

// Thing definition, position, orientation and type,
// plus skill/visibility flags and attributes.
namespace Doom
{
struct MapThing
{
    short x;
    short y;
    short angle;
    short type;
    short options;
};
} // namespace Doom

//-----------------------------------------------------------------------------
//
// $Log:$
//
//-----------------------------------------------------------------------------
